# --- Constants ---
VIDEO_CODEC = "h264_nvenc"
VIDEO_PRESET = "fast"
VIDEO_CQ = "24"
VIDEO_BITRATE = "0"
AUDIO_CODEC = "aac"
AUDIO_BITRATE = "192k"
MOVING_SPEED = 2
MOVING_LOGO_RELATIVE_HEIGHT = 1 / 12
MOVING_LOGO_ALPHA = 0.5
BANNER_TRACK_PIX_FMT = "yuva420p"
BANNER_GAP_COLOR = "black@0.0"
HWACCEL = "d3d12va"